"""added about me, last seen user model

Revision ID: 91092c61738c
Revises: 066f1fbec4c1
Create Date: 2020-09-17 09:39:40.353647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91092c61738c'
down_revision = '066f1fbec4c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
